language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
install:
    - pip install -e . --use-mirrors
    - pip install -r test_requirements.txt --use-mirrors
    - pip install -r tox_requirements.txt --use-mirrors
script:
    - make cov
after_success:
    - coveralls
