language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
install:
    - pip install -e .
    - pip install -r test_requirements.txt
    - pip install -r tox_requirements.txt
    - ./install-26-deps.sh
script:
    - make cov
    - xenon xenon -bB -mA -aA
after_success:
    - coveralls
