language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install -e . --use-mirrors
    - pip install -r test_requirements.txt --use-mirrors
    - pip install -r tox_requirements.txt --use-mirrors
script:
    - make cov
    - xenon xenon -bB -aA
after_success:
    - coveralls
